### ISSUE TITLE
Vagrant: throwing error relating to heapster replicas

### ISSUE THREAD

**Issue by willvrny** [apprenda/kismatic-provision#27]
I am receiving an error using provision with Vagrant. I am just following the steps in the README. This is with a fresh install of Vagrant and Virtualbox with no other VMs.

```bash
❯ ./kismatic install apply -f kismatic-cluster.yaml

Validating==========================================================================
Reading installation plan file "kismatic-cluster.yaml"                          [OK]
Validating installation plan file                                                              [ERROR]
- Heapster replicas 0 is not valid, must be greater than 0 
error validating plan: Plan file validation error prevents installation from proceeding
```

I removed the VM and the kismatic directory and started again from step 2. I still get the same error. Looking at the [planfile.go](https://github.com/apprenda/kismatic-provision/blob/master/provision/vagrant/planfile.go) it should be generating a kismatic-cluster.yaml file with:

```yaml
add_ons:
  heapster:
    disable: false
    options:
      heapster_replicas: 2
      influxdb_pvc_name: ""                                               # Provide the name of the persistent volume claim that you will create after installation. If not specified, the data will be stored in ephemeral storage.
  package_manager:
    disable: false
    provider: helm                                                        # Options: 'helm'
```

But when I look at the kismatic-cluster.yaml file thats been generated it's missing the above yaml.

When I add it in it works. 

Maybe the link in the docs pointing to an old version?
